using System;

namespace PetaPoco
{
    /// <summary>
    /// Specifies whether a property should be included in SQL AutoSelect queries.
    /// </summary>
    public enum IncludeInAutoSelect
    {
        /// <summary>
        /// The property should not be included in AutoSelect queries.
        /// </summary>
        No,

        /// <summary>
        /// The property should be included in AutoSelect queries.
        /// </summary>
        Yes
    }

    /// <summary>
    /// The ResultColumnAttribute class defines an attribute for POCO properties that should be used in <b>SQL queries only</b>, but ignored in UPDATE and INSERT operations.
    /// </summary>
    /// <remarks>
    /// This attribute marks properties that are mapped to a column, but should not be involved in any mutating operations on the database. The property value is updated by queries from the database, but the database column it maps to will not be changed to reflect changes in this property.
    /// <para/>Use the <see cref="IncludeInAutoSelect"/> property to dictate whether the decorated property is included in operations using PetaPoco's AutoSelect feature (default is <see cref="IncludeInAutoSelect.No"/>). AutoSelect queries are operations made using the "short form" syntax, without specifying the <c>SELECT [cols] FROM [table]</c> portion of the SQL statement. The inferred portion of the SQL statement is then automatically generated by PetaPoco based on generics or the called method's parameters.
    /// </remarks>
    [AttributeUsage(AttributeTargets.Property)]
    public class ResultColumnAttribute : ColumnAttribute
    {
        /// <summary>
        /// Gets or sets a value indicating whether the property should be included in AutoSelect queries.
        /// </summary>
        /// <value>
        /// Default value is <see cref="IncludeInAutoSelect.No"/>.
        /// </value>
        public IncludeInAutoSelect IncludeInAutoSelect { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResultColumnAttribute"/> class with default values.
        /// <para/><inheritdoc cref="ResultColumnAttribute"/>
        /// </summary>
        public ResultColumnAttribute()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResultColumnAttribute"/> class with the specified column name.
        /// <para/><inheritdoc cref="ResultColumnAttribute"/>
        /// </summary>
        /// <param name="name">The name of the column in the database.</param>
        public ResultColumnAttribute(string name)
            : this(name, IncludeInAutoSelect.No)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResultColumnAttribute"/> class with the specified AutoSelect inclusion setting.
        /// <para/><inheritdoc cref="ResultColumnAttribute"/>
        /// </summary>
        /// <param name="includeInAutoSelect">Specifies whether the property should be included in AutoSelect queries.</param>
        public ResultColumnAttribute(IncludeInAutoSelect includeInAutoSelect)
            : this(null, includeInAutoSelect)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResultColumnAttribute"/> class with the specified column name and AutoSelect inclusion setting.
        /// <para/><inheritdoc cref="ResultColumnAttribute"/>
        /// </summary>
        /// <param name="name">The name of the column in the database.</param>
        /// <param name="includeInAutoSelect">Specifies whether the property should be included in AutoSelect queries.</param>
        public ResultColumnAttribute(string name, IncludeInAutoSelect includeInAutoSelect)
            : base(name)
        {
            IncludeInAutoSelect = includeInAutoSelect;
        }
    }
}
