CREATE TABLE [People] (
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[FullName] NTEXT,
	[Age] BIGINT NOT NULL,
	[Height] INT NOT NULL,
	[Dob] DATETIME NOT NULL
);

CREATE TABLE [Orders] (
	[Id] INT IDENTITY(1,1) PRIMARY KEY,
	[PersonId] UNIQUEIDENTIFIER REFERENCES [People](Id),
	[PoNumber] NTEXT NOT NULL,
	[CreatedOn] DATETIME NOT NULL,
	[CreatedBy] NTEXT NOT NULL
);

CREATE TABLE [OrderLines] (
	[Id] INT IDENTITY(1,1) PRIMARY KEY,
	[OrderId] INT NOT NULL REFERENCES [Orders](Id),
	[Qty] SMALLINT NOT NULL,
	[SellPrice] NUMERIC(10, 4) NOT NULL
);