DROP TABLE IF EXISTS OrderLines;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS People;

CREATE TABLE People (
	Id VARCHAR(36) NOT NULL PRIMARY KEY, 
	FullName VARCHAR(255),
	Age BIGINT NOT NULL,
	Height INT NOT NULL,
	Dob DATETIME NULL
) ENGINE=INNODB;

CREATE TABLE Orders (
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	PersonId VARCHAR(36) NOT NULL,
	PoNumber VARCHAR(15) NOT NULL,
	CreatedOn DATETIME NOT NULL,
	CreatedBy VARCHAR(255) NOT NULL,
	FOREIGN KEY FK_Orders_People(PersonId) REFERENCES People(Id)
) ENGINE=INNODB;

CREATE TABLE OrderLines (
	Id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	OrderId INT NOT NULL,
	Qty SMALLINT NOT NULL,
	SellPrice DECIMAL(10, 4) NOT NULL,
	FOREIGN KEY FK_OrderLines_Orders(OrderId) REFERENCES Orders(Id)
) ENGINE=INNODB;

