DROP TABLE IF EXISTS "OrderLines";
DROP TABLE IF EXISTS "Orders";
DROP TABLE IF EXISTS "People";

CREATE TABLE "People" (
	"Id" UUID NOT NULL PRIMARY KEY,
	"FullName" VARCHAR(255),
	"Age" BIGINT NOT NULL,
	"Height" INT NOT NULL,
	"Dob" TIMESTAMP NULL
);

CREATE TABLE "Orders" (
	"Id" SERIAL PRIMARY KEY NOT NULL,
	"PersonId" UUID NOT NULL,
	"PoNumber" VARCHAR(15) NOT NULL,
	"CreatedOn" TIMESTAMP NOT NULL,
	"CreatedBy" VARCHAR(255) NOT NULL,
	CONSTRAINT "FK_Orders_People" FOREIGN KEY ("PersonId") REFERENCES "People"("Id")
);

CREATE TABLE "OrderLines" (
	"Id" SERIAL PRIMARY KEY NOT NULL,
	"OrderId" INT NOT NULL,
	"Qty" SMALLINT NOT NULL,
	"SellPrice" NUMERIC(10, 4) NOT NULL,
  CONSTRAINT "FK_OrderLines_Orders" FOREIGN KEY ("OrderId") REFERENCES "Orders"("Id")
);