name: Build and Test

on:
  push:
    branches:
      - 'feature/petapoco-v7'
#      - main
#  pull_requests:
#    branches:
#      - main'

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-source
        uses: actions/checkout@v2

      - uses: './.github/workflows/workflow-build-and-test.yml'
